version: 2

test: &test
  steps:
    - checkout

    - run:
        name: Run go mod
        command: |
          go mod download
          go mod vendor
    - run:
        name: Run vet
        command: go vet ./...
    - run:
        name: Run lint
        command: |
          GO111MODULE=off go get -u golang.org/x/lint/golint
          GO111MODULE=off golint -set_exit_status $(go list ./... | grep -v /vendor/)
    - run:
        name: Run staticcheck
        command: |
          GO111MODULE=off go get -u honnef.co/go/tools/cmd/staticcheck
          GO111MODULE=off staticcheck ./...

jobs:
  go-1.11-test:
    docker:
      - image: golang:1.11-stretch
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/y-yagi/eijiro
    <<: *test

  go-1.12-test:
    docker:
      - image: golang:1.12-stretch
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/y-yagi/eijiro
    <<: *test

  modules-update:
    docker:
      - image: golang:1.11-stretch
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/y-yagi/eijiro

    steps:
      - checkout
      - run:
          name: Run ci-modules-update
          command: |
            GO111MODULE=off go get -u github.com/y-yagi/ci-modules-update
            ci-modules-update -v
            ci-modules-update -u y-yagi -r y-yagi/eijiro

workflows:
  version: 2
  build:
    jobs:
      - go-1.11-test
      - go-1.12-test
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 22 * * 1"
          filters:
            branches:
              only: master
    jobs:
      - modules-update
